name: Codescan collection
on:
  workflow_call:
  
jobs:
  linter:
    uses: Labman4/workflow/.github/workflows/super-linter.yml@super-linter

  # codeql:
  #   uses: Labman4/workflow/.github/workflows/codeql-java.yml@codeql

  pmd:  
    uses: Labman4/workflow/.github/workflows/pmd.yml@pmd
