on: 
  workflow_call:

jobs:    
  update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.repository }}-concurrency-for-cache-maven
      cancel-in-progress: false
    steps:  
    - uses: actions/checkout@v3.5.3
   
#     - uses: actions/setup-java@v3
#       with:
#         distribution: 'liberica' # See 'Supported distributions' for available options
#         java-version: '17'

#     - uses: actions/cache@v3
#       with:
#         path: ~/.m2/
#         key: setup-graalvm-${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#         restore-keys: |
#           setup-graalvm-${{ runner.os }}-maven-
      
    - uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '17'
        set-java-home: 'true'
        cache: maven
        github-token: ${{ secrets.GITHUB_TOKEN }}
        
    - run: |
        rm -rf ~/.m2/repository/com/elpsykongroo
        
    - run: |
        mvn install -f base/pom.xml 
    - run: |
        mvn clean package install -DskipTests
  
