name: build or deploy
on: 
  workflow_call:
#     inputs:
#       deploy_secret:
#         type: string
#         required: false
jobs:
  auth:
    uses: Labman4/workflow/.github/workflows/native-image-postgres.yml@native-image
    secrets: inherit
    with:
      module: auth
      version: 1.0.0
      native: false
      secretPath: kv/app/native/auth
      
  # deployAuth:
  #   needs: auth
  #   uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
  #   with: 
  #     module: auth
      
  gateway: 
    needs: auth
    uses: Labman4/workflow/.github/workflows/native-image-gateway.yml@native-image
    secrets: inherit
    with:
      module: gateway
      version: 1.0.0
      native: false
      secretPath: kv/app/native/gateway
      
  # deployGateway:
  #   needs: gateway
  #   uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
  #   with: 
  #     module: gateway
      
  message: 
    needs: gateway
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: message
      version: 0.0.1
      native: false
      secretPath: kv/app/native/message

  # deployMessage:
  #   needs: message
  #   uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
  #   with: 
  #     module: message
      
  redis:
    uses: Labman4/workflow/.github/workflows/native-image-redis.yml@native-image
    secrets: inherit
    with:
      module: redis
      version: 1.0.0
      native: false
      secretPath: kv/app/native/redis

  # deployRedis:
  #   needs: redis
  #   uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
  #   with: 
  #     module: redis
      
  # elasticsearch:
  #   needs: redis
  #   uses: Labman4/workflow/.github/workflows/native-image-elasticsearch.yml@native-image
  #   secrets: inherit
  #   with:
  #     module: elasticsearch
  #     version: 1.0.0
  #     native: false
  #     secretPath: kv/app/native/es
      
  # deployES:
  #   needs: elasticsearch
  #   uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
  #   with: 
  #     module: elasticsearch
      
  storage:
    needs: redis
    uses: Labman4/workflow/.github/workflows/native-image-base.yml@native-image
    secrets: inherit
    with:
      module: storage
      version: 1.0.0
      native: false
      secretPath: kv/app/native/storage
      
  # deployStorage:
  #   needs: storage
  #   uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
  #   with: 
  #     module: storage
      
  kafka:
    needs: storage
    uses: Labman4/workflow/.github/workflows/native-image-kafka.yml@native-image
    secrets: inherit
    with:
      module: kafka
      version: 1.0.0
      native: false
      secretPath: kv/app/native/kafka
      
  # deployKafka:
  #   needs: kafka
  #   uses: Labman4/workflow/.github/workflows/deploy.yml@deploy
  #   with: 
  #     module: kafka
